# Created by: Ken Moore <ken@pcbsd.org>

PORTNAME=	lumina
PORTVERSION=	1.6.0
PORTEPOCH=	4
PKGNAMESUFFIX=	-devel
CATEGORIES=	x11

MAINTAINER=	lbartoletti@FreeBSD.org
COMMENT=	Lumina Desktop Environment (meta-port)

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=    lumina-core-devel>=0:x11/lumina-core-devel \
                lumina-coreutils-devel>=0:x11/lumina-coreutils-devel \
                lumina-archiver-devel>=0:deskutils/lumina-archiver-devel \
                lumina-calculator-devel>=0:deskutils/lumina-calculator-devel \
                lumina-fileinfo-devel>=0:deskutils/lumina-fileinfo-devel \
                lumina-fm-devel>=0:deskutils/lumina-fm-devel \
                lumina-mediaplayer-devel>=0:deskutils/lumina-mediaplayer-devel \
                lumina-pdf-devel>=0:deskutils/lumina-pdf-devel \
                lumina-photo-devel>=0:deskutils/lumina-photo-devel \
                lumina-screenshot-devel>=0:deskutils/lumina-screenshot-devel \
                lumina-textedit-devel>=0:deskutils/lumina-textedit-devel

USES=		metaport

CONFLICTS_INSTALL=	lumina lumina-1.2.*

.include <bsd.port.mk>
